<a href="https://colab.research.google.com/github/Jefferson-Aggor/Machine-Learning/blob/main/Wine_Type_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df = pd.read_csv('/content/wine_quality_merged.csv')

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [4]:
df.shape

(6497, 13)

In [5]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'type'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  type                  6497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [11]:
df.describe(include='all')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,white
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4898
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378,NaN
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255,NaN
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000,NaN
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000,NaN
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000,NaN
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000,NaN
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000,NaN

In [9]:
print(f'Number of missing values: {df.isna().sum().sum()}')

Number of missing values: 0

Step 2 – Prepare features and target

In [16]:
target = df['type']
X = df.drop('type', axis=1)

In [17]:
target.value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [22]:
# Map target values safely from df['type'] to ensure clean categories
target_mapping = {'red': 0, 'white': 1}
target = df['type'].map(target_mapping)

target.value_counts()

type
1    4898
0    1599
Name: count, dtype: int64

Step 3 – Split and scale

In [24]:
# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size=0.2, random_state=42, stratify=target)

In [26]:
# Standard Scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Step 4 – Train and compare kernels

In [41]:
def train_and_evaluate_svm(kernel, degree=3, C=1.0, show_report=True):
    model = SVC(C=C, kernel=kernel, degree=degree, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Kernel: {kernel} (Degree: {degree}, C: {C})")
    print("Accuracy:", round(accuracy, 3))
    print('\n')

    if show_report:
        print("\nClassification Report:\n", classification_report(y_test, y_pred))
        print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [42]:
train_and_evaluate_svm('linear', 0, 1.0)

Kernel: linear (Degree: 0, C: 1.0)
Accuracy: 0.998



Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       320
           1       1.00      1.00      1.00       980

    accuracy                           1.00      1300
   macro avg       1.00      1.00      1.00      1300
weighted avg       1.00      1.00      1.00      1300


Confusion Matrix:
 [[319   1]
 [  2 978]]

In [43]:
train_and_evaluate_svm('rbf', 0, 1.0)

Kernel: rbf (Degree: 0, C: 1.0)
Accuracy: 0.997



Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       320
           1       1.00      1.00      1.00       980

    accuracy                           1.00      1300
   macro avg       1.00      0.99      1.00      1300
weighted avg       1.00      1.00      1.00      1300


Confusion Matrix:
 [[317   3]
 [  1 979]]

In [44]:
train_and_evaluate_svm(kernel='poly', degree=3)

Kernel: poly (Degree: 3, C: 1.0)
Accuracy: 0.995



Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99       320
           1       0.99      1.00      1.00       980

    accuracy                           0.99      1300
   macro avg       1.00      0.99      0.99      1300
weighted avg       0.99      0.99      0.99      1300


Confusion Matrix:
 [[314   6]
 [  1 979]]

In [47]:
C = [0.5, 5]

for c in C:
    print(f"C: {c}\n")
    train_and_evaluate_svm(kernel='linear', degree=0, C=c, show_report=False)
    train_and_evaluate_svm(kernel='poly', degree=3, C=c, show_report=False)
    train_and_evaluate_svm(kernel='rbf', degree=0, C=c, show_report=False)

C: 0.5

Kernel: linear (Degree: 0, C: 0.5)
Accuracy: 0.998


Kernel: poly (Degree: 3, C: 0.5)
Accuracy: 0.992


Kernel: rbf (Degree: 0, C: 0.5)
Accuracy: 0.996


C: 5

Kernel: linear (Degree: 0, C: 5)
Accuracy: 0.998


Kernel: poly (Degree: 3, C: 5)
Accuracy: 0.995


Kernel: rbf (Degree: 0, C: 5)
Accuracy: 0.997